Test all mono

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -61,3 +61,66 @@ jobs:
         name: tests-zip
         path: wine-mono-*-tests.zip
 
+  linux-test:
+
+    runs-on: ubuntu-20.04
+    needs: build
+
+    steps:
+    - name: Remove packages require EULA
+      run: sudo apt remove msodbcsql17 linux-azure linux-cloud-tools-azure linux-headers-azure linux-image-azure linux-tools-azure -y 1>&2
+    - name: Install Wine
+      run: |
+        sudo dpkg --add-architecture i386 1>&2
+        wget -nc https://dl.winehq.org/wine-builds/winehq.key 1>&2
+        sudo apt-key add winehq.key 1>&2
+        sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main' 1>&2
+        sudo apt update 1>&2
+        sudo apt install --install-recommends -y winehq-devel 1>&2
+    - name: Download Wine Mono msi
+      uses: actions/download-artifact@v2
+      with:
+        name: make msi output
+    - name: Install Wine Mono msi
+      run: wine msiexec /i wine-mono-*.msi 1>&2
+    - name: Run 64-bit Wine mscoree tests
+      run: |
+        wget -nc 'http://test.winehq.org/builds/winetest64-latest.exe' 1>&2
+        wine winetest64-latest.exe -x winetest64 >/dev/null
+        for testname in `wine winetest64/mscoree_test.exe --list 2>/dev/null|sed 's/\r//'|tail -n +2`; do
+          echo BEGIN $testname TEST >>winetest64-output.log
+          wine64 winetest64/mscoree_test.exe $testname >>winetest64-output.log 2>&1 || printf '::warning mscoree:%s test failed\n' $testname
+          echo END $testname TEST >>winetest64-output.log
+        done
+    - name: Run 32-bit Wine mscoree tests
+      run: |
+        wget -nc 'http://test.winehq.org/builds/winetest-latest.exe' 1>&2
+        wine winetest-latest.exe -x winetest >/dev/null
+        for testname in `wine winetest/mscoree_test.exe --list 2>/dev/null|sed 's/\r//'|tail -n +2`; do
+          echo BEGIN $testname TEST >>winetest-output.log
+          wine winetest/mscoree_test.exe $testname >>winetest-output.log 2>&1 || printf '::warning mscoree:%s test failed\n' $testname
+          echo END $testname TEST >>winetest-output.log
+        done
+    - name: Download Wine Mono msi
+      uses: actions/download-artifact@v2
+      with:
+        name: tests-zip
+    - name: Run Mono tests
+      run: |
+        unzip wine-mono-*-tests.zip
+        cd tests
+        wine run-tests.exe -skip-list:skip-always.txt -pass-list:wine-passing.txt -fail-list:wine-failing.txt 1>&2
+        
+  win-test:
+    runs-on: windows-2019
+    needs: build
+    steps:
+    - name: Download Wine Mono msi
+      uses: actions/download-artifact@v2
+      with:
+        name: tests-zip
+    - name: Run Mono tests
+      run: |
+        unzip wine-mono-*-tests.zip
+        cd tests
+        run-on-windows.bat
